language: ruby
rvm:
  - "2.2.1"
script: bundle exec cucumber -r features features
before_install:
  - export BUNDLE_GEMFILE=$PWD/homework_tester/Gemfile
install: cd homework_tester && bundle install --jobs=3 --retry=3
sudo: false
